import { app, BrowserWindow, ipcMain, dialog, shell } from 'electron';
import { initializeDatabase } from './database';
import fs from 'fs';
import path from 'path';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}
const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true, // should be true
      nodeIntegration: false, // should be false
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async () => {
  await initializeDatabase();
  createWindow();
});


// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

ipcMain.handle('open-folder-dialog', async (event) => {
  const { canceled, filePaths } = await dialog.showOpenDialog({
    properties: ['openDirectory']
  });
  if (canceled) {
    return null; // This is serializable
  } else {
    return filePaths[0]; // This should be a string, which is serializable
  }
});

ipcMain.handle('read-dir', async (event, dirPath) => {
  try {
    const files = await fs.promises.readdir(dirPath);
    return files.map(file => ({
      name: file,
      path: path.join(dirPath, file),
    }));
  } catch (error) {
    console.error('Failed to read directory:', error);
    return { error: `Failed to read directory at path ${dirPath}: ${error.message}` };
  }
});



ipcMain.handle('is-directory', async (event, filePath) => {
  try {
    const stats = await fs.promises.stat(filePath);
    return { isDirectory: stats.isDirectory() }; // Send back a plain object
  } catch (error) {
    // Again, throw a plain object with the error message
    throw { message: error.message };
  }
});

ipcMain.handle('open-path', async (event, filePath) => {
  try {
    await shell.openPath(filePath);
    return true;
  } catch (error) {
    // And once more, throw a plain object with the error message
    throw { message: error.message };
  }
});


ipcMain.handle('join-path', (event, ...paths) => {
  return path.join(...paths);
});


const listFiles = (dirPath) => {
  return new Promise((resolve, reject) => {
    fs.readdir(dirPath, { withFileTypes: true }, (err, files) => {
      if (err) {
        reject(err);
        return;
      }
      resolve(files.map(file => ({
        name: file.name,
        path: path.join(dirPath, file.name),
        isDirectory: file.isDirectory()
      })));
    });
  });
};

ipcMain.handle('list-files', async (event, dirPath) => {
  try {
    const files = await listFiles(dirPath);
    return files;
  } catch (error) {
    console.error('Error listing files:', error);
    throw error;
  }
});