name: Electron App CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build Electron app
      run: npm run build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: electron-app-${{ matrix.os }}
        path: |
          dist/**/*.exe
          dist/**/*.dmg
          dist/**/*.AppImage

  upload-to-supabase:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3

    - name: Install Supabase CLI
      run: npm install -g supabase

    - name: Upload to Supabase Storage
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        for file in electron-app-*/**/*; do
          if [ -f "$file" ]; then
            supabase storage upload --bucket app-downloads "$file" "$file" --public
          fi
        done
