name: Build and Upload to Supabase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            build_command: build:linux
            file_pattern: "release/build/linux-unpacked/**/*"
          - os: windows-latest
            build_command: build:win
            file_pattern: "release/build/win-unpacked/Treash.exe"
          - os: macos-latest
            build_command: build:mac
            file_pattern: "release/build/*.dmg"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run ${{ matrix.build_command }}

    - name: List build directory
      run: ls -R release/build

    - name: Upload to Supabase
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        APP_FILES=$(ls ${{ matrix.file_pattern }} 2>/dev/null || echo "")
        if [ -z "$APP_FILES" ]; then
          echo "No files found matching pattern: ${{ matrix.file_pattern }}"
          exit 1
        fi
        for APP_FILE in $APP_FILES; do
          echo "Uploading $APP_FILE to Supabase"
          curl -X POST "${SUPABASE_URL}/storage/v1/object/app-downloads/${{ matrix.os }}/$(basename $APP_FILE)" \
            -H "Authorization: Bearer $SUPABASE_KEY" \
            -H "Content-Type: application/octet-stream" \
            --data-binary "@$APP_FILE"
        done
